### PR TITLE
Treat new char variable as char

### PR DESCRIPTION
**Pull request by HencoSmith**
Add: type for values store either 'CHAR' or 'INT' display will be char for char

Internally chars are treated as unicode

You can verify by adding a char then bit shifting to see the unicode character change, block characters means the unicode char is not representable on the html page or at least it doesn't know how to display it correctly, this can occur when you shift to a strange value.

Note operations other than bit shifting doesn't seem to work atm? I switched to master and verified the same so I don't think the code I added caused it?

### CODE REVIEW

**Comment by unsuitable001** [comment]
Well done @HencoSmith ! I haven't run the code yet. But, as I can see from diff, it seems fine to me.
Suggestion : as char is always 8 bit, you can check that & turn those exceeding bits (on left side) to `0`.
Possible approach : use bitwise and `&` with the `variable value` and `0000....000011111111`

**Comment by unsuitable001** [comment]
> Note operations other than bit shifting doesn't seem to work atm? I switched to master and verified the same so I don't think the code I added caused it?

As far as I can test, everything is working fine in master branch. I suggest you to look at the `README.md` file & look at the keybindings & selection types. You can suggest changes there too.

**Comment by unsuitable001** [comment]
> Note operations other than bit shifting doesn't seem to work atm? I switched to master and verified the same so I don't think the code I added caused it?

Sadly, your patch caused it. It's working fine in the master branch.
I can point out the issue. Please fix it.

In previous code, `window[varName] = value`. But, now (after your patch), it's `window[varName] = { value, type }`

When doing mathematical operations, see from `line 364`, `line 418` & where ever
 the `modifyVal` & `window[varName]` is used, is broken. Fix them. (You have changed some of the places, but forgot most of it.)

**Comment by unsuitable001** [comment]
I can suggest you a better approach that will require less code alteration from existing codebase.
Revert back to my master branch commit. add an optional argument to `addVar` function, like `isChar` which defaults to `false`. Then add that `isChar` flag to the `html data attribute` for future reference.

In this way, far less part of the code will need modification. & the `window` object will be less bloated. So, less memory consumption :smile:

**Comment by HencoSmith** [comment]
Ah I see sorry, I was searching for window[varName] when doing replacements, not window[x].

I treated the store value as an object window[x] = { type, value } since you might want to add more fields in the future for instance an ID since at the moment if you add 2 variables with the same name the second doesn't display correct. 

Although technically this kind of info should be stored in local storage and then when the user opens the page again his data is still there.

Let me change it a bit and then you can let me know what you think

**Pull request closed without merging**
