### PR TITLE
Resolving issue5, A Standalone Desktop App with Electron.js

### PR DESCRIPTION
**Pull request by newvertex**
Resolving https://github.com/unsuitable001/BitViz/issues/5 
Add desktop version with electron.js in desktop sub directory,
Use electron-builder to build the standalone single installer file, run `yarn build` command to build and generate installer,

### CODE REVIEW

**Comment by unsuitable001** [comment]
Excellent work @newvertex . I'll test it then merge it.

**Comment by newvertex** [comment]
@unsuitable001 I've found a variable name conflict, I've pushed a commit for this.

**Comment by unsuitable001** [comment]
@newvertex Do one more thing. Please try use `index.html` & `index.js` from the repo root directly. Otherwise, when we need to patch either of those files, we have to patch files in both folders `/` & `desktop`

**Comment by newvertex** [comment]
@unsuitable001 Ok that's it, I've changed the structure and some of codes to keep it simple in root directory

**Comment by newvertex** [comment]
I've made some change to fix the 4 space problem and squashed commits, check it again.

**Comment by unsuitable001** [comment]
@newvertex Great work :confetti_ball: 
Can you open this PR for development branch? :smile: 
I actually don't want to modify the master branch. I need to do some changes.

**Comment by newvertex** [comment]
I've changed the base branch to development

**Pull request merged**
