### PR TITLE
Update: use modal instead of js prompt for user input

### PR DESCRIPTION
**Pull request by newvertex**
Use modal instead of js prompt for user input and fix some styling about user input and show help message modal.

### CODE REVIEW

**Comment by unsuitable001** [comment]
There are too many spacing changes. Use 4 space tab please & commit. Otherwise, seems fine. I'll let you know after I test.

**Comment by newvertex** [comment]
@unsuitable001 that's my bad, sorry for that, I've pushed another commit ;-)

**Comment by unsuitable001** [comment]
Still have the same issue :(

**Comment by newvertex** [comment]
Ok finally I've squashed it, now check it out.

**Pull request closed without merging**
