### PR TITLE
Issue Text Added in  Readme md file

### PR DESCRIPTION
**Pull request by mrahmadusama**

### CODE REVIEW

**Comment by unsuitable001** [comment]
I can't understand what you are trying to patch.
Please elaborate :smile:

**Comment by unsuitable001** [comment]
Try to improve the PR (only if you want to continue) within 24hrs or, I'll label it as `invalid` and `close` the PR until you respond. Thank You.

**Comment by mrahmadusama** [comment]
I'll Improve. I was trying to say please improve the box sizes as much as
possible so doesn't overlap the text.
Thanks

**Comment by unsuitable001** [comment]
So, make changes as you like & then make a PR with changes.
Best of luck. Appreciate your efforts. 😊

**Comment by unsuitable001** [comment]
This PR seems inactive to me.

**Comment by mrahmadusama** [comment]
Been Busy I'll fix it today.
Thanks.

**Pull request closed without merging**
